// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

//npx prisma generate Reads schema, generates TypeScript client code
// npx prisma migrate dev Creates SQL migration files + runs them
// npx prisma migrate dev --name init

// npx prisma migrate reset reset the db
// npx prisma studio Opens visual database browser
// npx prisma db pull Reads existing DB and generates schema
// npx prisma db seed-data

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    //path: "prisma/migrations",
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
