import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    //path: "prisma/migrations",
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});


// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

//npx prisma generate Reads schema, generates TypeScript client code
// npx prisma migrate dev Creates SQL migration files + runs them
// npx prisma migrate dev --name init

// npx prisma migrate reset reset the db
// npx prisma studio Opens visual database browser
// npx prisma db pull Reads existing DB and generates schema
// npx prisma db seed

//npx prisma migrate status
//Loaded Prisma config from prisma.config.ts.

//Datasource "db": PostgreSQL database "biomedical", schema "pdhs" at "localhost:5432"

//2 migrations found in prisma/migrations
//Following migrations have not yet been applied:
//20260607065001_init
//20260607184127_optinal_manufcture

//To apply migrations in development run prisma migrate dev.
//To apply migrations in production run prisma migrate deploy.
