export enum Permission {

  INVENTORY_VIEW,
  INVENTORY_CREATE,
  INVENTORY_UPDATE,
  INVENTORY_DELETE,

  EQUIPMENT_VIEW,
  EQUIPMENT_CREATE,
  EQUIPMENT_UPDATE,
  EQUIPMENT_DELETE,

  REPAIR_REQUEST_VIEW,
  REPAIR_REQUEST_CREATE,
  REPAIR_REQUEST_UPDATE,

  WORK_ORDER_VIEW,
  WORK_ORDER_ASSIGN,
  WORK_ORDER_COMPLETE,

  PROCUREMENT_VIEW,
  PROCUREMENT_CREATE,
  PROCUREMENT_APPROVE,

  USER_VIEW,
  USER_CREATE,
  USER_UPDATE,
  USER_DELETE
}